[package]
name = "rust-collision-sim"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "FeO"
path = "main.rs"

[dependencies]
piston = "0.55.0"
piston2d-graphics = "0.44.0"
pistoncore-glutin_window = "0.72.0"
piston2d-opengl_graphics = "0.84.0"
rand = "0.8.4"
